### ISSUE TITLE
Communication: between micro-frontends and the host app. Not all micro-frontends may use module-federation.

### ISSUE THREAD

**Issue by rang-ali** [aperkaz/micro-frontend-template#4]
Implementation suggestion:
Provide a set of small typed functions as a separate module. The module can be used by remote applications that are mounted as either iframes or micro-apps.

The api could look something like this:
```
myModule.router.go('/home') // call a router method
myModule.notify('hello world') //  trigger a notification in the host app
```

Ideally, the signature of the module API should look the same regardless if the remote app is mounted as an iframe or micro-app.
This could be solved through a simple check inside of the `myModule`-class.

i.e. 

```
class myModule() {
  constructor() {
    // ...
  }
  baseFn() {
    const baseFn = isMountedInsideOfIframe ? window.parent.document.__HOST__COMMUNICATOR__ : window.__HOST__COMMUNICATOR
  }

  router() {
    // ...
    return {
      go: baseFn().go,
    }
  }

}

```

Inside of the host application, register a global object that holds all the provided functions.

**Comment by aperkaz** [comment]
Closing in favour of https://github.com/aperkaz/micro-frontend-template/discussions/5
